package org.galacticware.griddle.keyboarddefinition.layouts.converter.flickboard.converted

//import org.galacticware.griddle.model.operation.shiftBoardLeft
//import org.galacticware.griddle.model.operation.shiftBoardRight
import org.galacticware.griddle.domain.operation.simpleInput
import org.galacticware.griddle.domain.gesture.GestureType.CLICK
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_DOWN
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_DOWN_LEFT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_DOWN_RIGHT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_LEFT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_RIGHT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_UP
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_UP_LEFT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_UP_RIGHT
import org.galacticware.griddle.domain.griddlebutton.builder.GriddleButtonBuilder.Companion.makeClassicGestureButton
import org.galacticware.griddle.domain.keybinder.KeyBinder.Companion.gestureSet
import org.galacticware.griddle.domain.util.caseSensitive

/**
 * This file was generated by the FlickBoardConverter.kt script.
 * The original file should be kept in the same directory as this file.
 */



private val _FAThumbKey_button0_0 = makeClassicGestureButton(
	rowStart = 0, colStart = 0, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("د")),
		gestureSet(SWIPE_DOWN, simpleInput, threeChars = caseSensitive("ض")),
		gestureSet(SWIPE_DOWN_RIGHT, simpleInput, threeChars = caseSensitive("ص")),
	)
)
private val _FAThumbKey_button0_1 = makeClassicGestureButton(
	rowStart = 0, colStart = 1, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("ر")),
		gestureSet(SWIPE_RIGHT, simpleInput, threeChars = caseSensitive("ژ")),
		gestureSet(SWIPE_DOWN_LEFT, simpleInput, threeChars = caseSensitive("ق")),
		gestureSet(SWIPE_DOWN, simpleInput, threeChars = caseSensitive("ز")),
		gestureSet(SWIPE_DOWN_RIGHT, simpleInput, threeChars = caseSensitive("ف")),
	)
)
private val _FAThumbKey_button0_2 = makeClassicGestureButton(
	rowStart = 0, colStart = 2, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("و")),
		gestureSet(SWIPE_DOWN_LEFT, simpleInput, threeChars = caseSensitive("ع")),
		gestureSet(SWIPE_DOWN, simpleInput, threeChars = caseSensitive("ء")),
	)
)
private val _FAThumbKey_button1_0 = makeClassicGestureButton(
	rowStart = 1, colStart = 0, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("ن")),
		gestureSet(SWIPE_UP_RIGHT, simpleInput, threeChars = caseSensitive("ح")),
		gestureSet(SWIPE_RIGHT, simpleInput, threeChars = caseSensitive("ج")),
		gestureSet(SWIPE_DOWN_RIGHT, simpleInput, threeChars = caseSensitive("چ")),
	)
)
private val _FAThumbKey_button1_1 = makeClassicGestureButton(
	rowStart = 1, colStart = 1, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("ا")),
		gestureSet(SWIPE_UP_LEFT, simpleInput, threeChars = caseSensitive("ذ")),
		gestureSet(SWIPE_UP, simpleInput, threeChars = caseSensitive("ب")),
		gestureSet(SWIPE_UP_RIGHT, simpleInput, threeChars = caseSensitive("پ")),
		gestureSet(SWIPE_LEFT, simpleInput, threeChars = caseSensitive("خ")),
		gestureSet(SWIPE_RIGHT, simpleInput, threeChars = caseSensitive("س")),
		gestureSet(SWIPE_DOWN_LEFT, simpleInput, threeChars = caseSensitive("آ")),
		gestureSet(SWIPE_DOWN, simpleInput, threeChars = caseSensitive("ل")),
		gestureSet(SWIPE_DOWN_RIGHT, simpleInput, threeChars = caseSensitive("ش")),
	)
)
private val _FAThumbKey_button1_2 = makeClassicGestureButton(
	rowStart = 1, colStart = 2, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("م")),
		gestureSet(SWIPE_UP_LEFT, simpleInput, threeChars = caseSensitive("غ")),
		gestureSet(SWIPE_LEFT, simpleInput, threeChars = caseSensitive("ک")),
		gestureSet(SWIPE_DOWN_LEFT, simpleInput, threeChars = caseSensitive("گ")),
	)
)
private val _FAThumbKey_button2_0 = makeClassicGestureButton(
	rowStart = 2, colStart = 0, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("ت")),
		gestureSet(SWIPE_UP_RIGHT, simpleInput, threeChars = caseSensitive("ث")),
	)
)
private val _FAThumbKey_button2_1 = makeClassicGestureButton(
	rowStart = 2, colStart = 1, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("ی")),
		gestureSet(SWIPE_LEFT, simpleInput, threeChars = caseSensitive("؟")),
		gestureSet(SWIPE_RIGHT, simpleInput, threeChars = caseSensitive("ئ")),
		gestureSet(SWIPE_DOWN_LEFT, simpleInput, threeChars = caseSensitive("*")),
		gestureSet(SWIPE_DOWN, simpleInput, threeChars = caseSensitive(".")),
		gestureSet(SWIPE_DOWN_RIGHT, simpleInput, threeChars = caseSensitive("ـ")),
	)
)
private val _FAThumbKey_button2_2 = makeClassicGestureButton(
	rowStart = 2, colStart = 2, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gestureSet(CLICK, simpleInput, threeChars = caseSensitive("ه")),
		gestureSet(SWIPE_UP_LEFT, simpleInput, threeChars = caseSensitive("ط")),
		gestureSet(SWIPE_UP, simpleInput, threeChars = caseSensitive("ظ")),
		gestureSet(SWIPE_LEFT, simpleInput, threeChars = caseSensitive("ۀ")),
	)
)