package org.galacticware.griddle.keyboarddefinition.layouts.converter.flickboard.converted

//import org.galacticware.griddle.model.operation.shiftBoardLeft
//import org.galacticware.griddle.model.operation.shiftBoardRight
import org.galacticware.griddle.domain.operation.simpleInput
import org.galacticware.griddle.domain.gesture.GestureType.CLICK
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_DOWN
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_DOWN_LEFT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_DOWN_RIGHT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_LEFT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_RIGHT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_UP
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_UP_LEFT
import org.galacticware.griddle.domain.gesture.GestureType.SWIPE_UP_RIGHT
import org.galacticware.griddle.domain.griddlebutton.builder.GriddleButtonBuilder.Companion.makeClassicGestureButton
import org.galacticware.griddle.domain.keybinder.KeyBinder.Companion.gesture
import org.galacticware.griddle.domain.util.caseSensitive

/**
 * This file was generated by the FlickBoardConverter.kt script.
 * The original file should be kept in the same directory as this file.
 */



private val _FAMessagEase_button0_0 = makeClassicGestureButton(
	rowStart = 0, colStart = 0, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("ه")),
		gesture(SWIPE_RIGHT, simpleInput, threeStrings = caseSensitive("ـ")),
		gesture(SWIPE_DOWN, simpleInput, threeStrings = caseSensitive("ۀ")),
		gesture(SWIPE_DOWN_RIGHT, simpleInput, threeStrings = caseSensitive("ق")),
	)
)
private val _FAMessagEase_button0_1 = makeClassicGestureButton(
	rowStart = 0, colStart = 1, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("ب")),
		gesture(SWIPE_DOWN_LEFT, simpleInput, threeStrings = caseSensitive("ض")),
		gesture(SWIPE_DOWN, simpleInput, threeStrings = caseSensitive("خ")),
		gesture(SWIPE_DOWN_RIGHT, simpleInput, threeStrings = caseSensitive("پ")),
	)
)
private val _FAMessagEase_button0_2 = makeClassicGestureButton(
	rowStart = 0, colStart = 2, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("م")),
		gesture(SWIPE_DOWN_LEFT, simpleInput, threeStrings = caseSensitive("چ")),
	)
)
private val _FAMessagEase_button1_0 = makeClassicGestureButton(
	rowStart = 1, colStart = 0, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("ی")),
		gesture(SWIPE_UP_RIGHT, simpleInput, threeStrings = caseSensitive("ص")),
		gesture(SWIPE_RIGHT, simpleInput, threeStrings = caseSensitive("ش")),
		gesture(SWIPE_DOWN_RIGHT, simpleInput, threeStrings = caseSensitive("ط")),
	)
)
private val _FAMessagEase_button1_1 = makeClassicGestureButton(
	rowStart = 1, colStart = 1, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("ا")),
		gesture(SWIPE_UP_LEFT, simpleInput, threeStrings = caseSensitive("ف")),
		gesture(SWIPE_UP, simpleInput, threeStrings = caseSensitive("ح")),
		gesture(SWIPE_UP_RIGHT, simpleInput, threeStrings = caseSensitive("ج")),
		gesture(SWIPE_LEFT, simpleInput, threeStrings = caseSensitive("س")),
		gesture(SWIPE_RIGHT, simpleInput, threeStrings = caseSensitive("آ")),
		gesture(SWIPE_DOWN_LEFT, simpleInput, threeStrings = caseSensitive("ل")),
		gesture(SWIPE_DOWN, simpleInput, threeStrings = caseSensitive("ت")),
		gesture(SWIPE_DOWN_RIGHT, simpleInput, threeStrings = caseSensitive("ک")),
	)
)
private val _FAMessagEase_button1_2 = makeClassicGestureButton(
	rowStart = 1, colStart = 2, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("ر")),
		gesture(SWIPE_UP_LEFT, simpleInput, threeStrings = caseSensitive("ژ")),
		gesture(SWIPE_LEFT, simpleInput, threeStrings = caseSensitive("ز")),
		gesture(SWIPE_DOWN_LEFT, simpleInput, threeStrings = caseSensitive("ع")),
	)
)
private val _FAMessagEase_button2_0 = makeClassicGestureButton(
	rowStart = 2, colStart = 0, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("و")),
		gesture(SWIPE_UP_RIGHT, simpleInput, threeStrings = caseSensitive("ؤ")),
	)
)
private val _FAMessagEase_button2_1 = makeClassicGestureButton(
	rowStart = 2, colStart = 1, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("ن")),
		gesture(SWIPE_UP_LEFT, simpleInput, threeStrings = caseSensitive("ظ")),
		gesture(SWIPE_UP, simpleInput, threeStrings = caseSensitive("ث")),
		gesture(SWIPE_UP_RIGHT, simpleInput, threeStrings = caseSensitive("غ")),
		gesture(SWIPE_LEFT, simpleInput, threeStrings = caseSensitive("ء")),
		gesture(SWIPE_RIGHT, simpleInput, threeStrings = caseSensitive("أ")),
		gesture(SWIPE_DOWN, simpleInput, threeStrings = caseSensitive(".")),
		gesture(SWIPE_DOWN_RIGHT, simpleInput, threeStrings = caseSensitive("ئ")),
	)
)
private val _FAMessagEase_button2_2 = makeClassicGestureButton(
	rowStart = 2, colStart = 2, rowSpan = 1, colSpan = 1,
	gestureSet = mutableSetOf(
		gesture(CLICK, simpleInput, threeStrings = caseSensitive("د")),
		gesture(SWIPE_UP_LEFT, simpleInput, threeStrings = caseSensitive("گ")),
		gesture(SWIPE_LEFT, simpleInput, threeStrings = caseSensitive("ذ")),
	)
)